### ISSUE TITLE
vendor directory is missing when using composer

### ISSUE THREAD

**Issue by hypeJunction** [smottt/WideImage#6]
vendor directory is included in the repository, but due to .gitignore rules it is not checked out during composer install. Since the de77 is already in the repo, I suggest to just remove vendor from .gitignore

**Comment by smottt** [comment]
Not sure what you mean with "it is not checked out during composer install"? That might be because there were no actual dependencies in composer.json. I've added phpunit as a dev dependency, that should fix it for dev builds.

**Comment by hypeJunction** [comment]
I new I wasn't dreaming about this. 
`.gitingore` says `vendor/`, so it ignores all nested vendor folders. Should be `/vendor/`

**Comment by hypeJunction** [comment]
Also vendor dir location is not PSR compliant, so you need to add a classmap:

```
    "autoload": {
		"classmap": [
			"lib/vendor/de77/"
		]
	}
```
