### ISSUE TITLE
Packagist releases

### ISSUE THREAD

**Issue by hypeJunction** [smottt/WideImage#9]
You have bumped the PHP version to 5.6, which is breaking my code now. Packagist only lists master, and I can no longer use a commit SHA as a constraint. It would be great if you could set up auto updates to packagist.

**Comment by hypeJunction** [comment]
Also I think you should release 2.0 instead of 1.1 to comply with semver if you are introducing a PHP version change.

**Comment by smottt** [comment]
My mistake, sorry about that. I was sure that the 1.1 release was listed on packagist, should have checked that. I intend to release this as 2.0 indeed. Will fix the versions today. Thanks for reporting.

**Comment by smottt** [comment]
New release v1.1.1 is now available. It fixes the version and PHP constraint issues. All of the new functionality will be relased as v2.0.0. Thanks again for reporting this.

**Comment by hypeJunction** [comment]
Thanks
